### ISSUE TITLE
How to destroy all items in objectPool? 

### ISSUE THREAD

**Issue by justinLifelike** [onewheelstudio/Adventures-in-C-Sharp#1]
![image](https://user-images.githubusercontent.com/89152236/167444777-b471db3d-8a8a-42f0-a349-42bed7c336f3.png)

I want to destroy all items in the object pool so that they are not in the scene anymore. 
I have written DestroyPool for this purpose but I can't seem to find a way to access this function from outside this function. 

I have tried to do it by writing the RemoveAllSpawnedObjects() script but that seems to be wrong as the stack will also appear to be empty. 

![image](https://user-images.githubusercontent.com/89152236/167445370-6fe785c9-8915-4838-a0b6-d42ec9e7ef31.png)

**Comment by justinLifelike** [comment]
using System.Collections.Generic;
using UnityEngine;
using System;

namespace OWS.ObjectPooling
{

    //The object pool definition 
    //The Object pool itself has a generic parameter T and implements the IPool interface.
    //T is then constrained to be a monobehaviour that must also implement the IPoolable interface.
    public class ObjectPool<T> : IPool<T> where T : MonoBehaviour, IPoolable<T>
    {

        // a constructor that takes in a number of objects to pre-spawn using the Spawn function
        public ObjectPool(GameObject pooledObject, int numToSpawn = 0)
        {
            this.prefab = pooledObject;
            Spawn(numToSpawn);
        }   

        // a constructor that takes in the prefab aswell as the references for the pullObject and pushObject actions. 
        public ObjectPool(GameObject pooledObject, Action<T> pullObject, Action<T> pushObject, int numToSpawn = 0)
        {
            this.prefab = pooledObject;
            this.pullObject = pullObject;
            this.pushObject = pushObject;
            Spawn(numToSpawn);
        }

        // 2 optional actions. These actions can be assigned in a constructor
        // This allows you to call function everytime an object is pulled out of the pool or pushed back to the pool.
        // This could be used to play SFX, increment a counter etc. 
        private System.Action<T> pullObject;
        private System.Action<T> pushObject;

        // The stack that holds all the pooled objects
        private Stack<T> pooledObjects = new Stack<T>();

        //It’s this gameObject that will be instantiated if and when the pool runs out of objects in the stack. 
        private GameObject prefab;

        // a property to count the number of objects in the pool.
        // No direct use
        public int pooledCount
        {
            get
            {
                return pooledObjects.Count;
            }
        }


        // Is called whenever an object from the pool is need 
        // First we check if there are any objects in the pool, if there are we pop one out 
        // The gameObject is then set to active and the Initialize function on the Ipoolable object is called 
        public T Pull()
        {
            T t;
            if (pooledCount > 0)
                t = pooledObjects.Pop();
            else
                t = GameObject.Instantiate(prefab).GetComponent<T>();

            t.gameObject.SetActive(true); //ensure the object is on
            t.Initialize(Push); 
            // We are providing a reference to the push function
            // The push function is the function used to return an object to the pool
            // This means the spwaned object has reference to this function and can return itself to the pool. 

            // We then check if the pullObject action was assigned and if it was we invoke it and pass in the object being spawned.
            //allow default behavior and turning object back on
            pullObject?.Invoke(t);

            //We return the object so that whatever object asked for it, can have a reference to it. 
            return t;
        }

        // Several overloads for the Pull function to make the object pool more useful and user friendly 
        // These allow the position and rotation of the object to be set when pulling it
        public T Pull(Vector3 position)
        {
            T t = Pull();
            t.transform.position = position;
            return t;
        }

        public T Pull(Vector3 position, Quaternion rotation)
        {
            T t = Pull();
            t.transform.position = position;
            t.transform.rotation = rotation;
            return t;
        }

        // function that return a gameObject, as in some cases this is what is really needed and not the poolable object component. 
        public GameObject PullGameObject()
        {
            return Pull().gameObject;
        }

        public GameObject PullGameObject(Vector3 position)
        {
            GameObject go = Pull().gameObject;
            go.transform.position = position;
            return go;
        }

        public GameObject PullGameObject(Vector3 position, Quaternion rotation)
        {
            GameObject go = Pull().gameObject;
            go.transform.position = position;
            go.transform.rotation = rotation;
            return go;
        }

        //The push function is pretty simple. It takes in the object and pushes it onto the stack.
        //It then checks if the pushObject action was assigned and invokes it if it was.
        //Lastly, the gameObject is turned off. 
        public void Push(T t)
        {
            pooledObjects.Push(t);

            //create default behavior to turn off objects
            pushObject?.Invoke(t);

            t.gameObject.SetActive(false);
        }

        private void Spawn(int number)
        {
            T t;

            for (int i = 0; i < number; i++)
            {
                t = GameObject.Instantiate(prefab).GetComponent<T>();
                pooledObjects.Push(t);
                t.gameObject.SetActive(false);
            }
        }

        public void DestroyPool()
        {
            
            foreach (T item in pooledObjects)
            {
                UnityEngine.Object.Destroy(item.gameObject);
                item.GetComponent<PoolObject>().DestroyThis();
                Debug.Log("Destroyed");
            }

            //for (int i = 0; i < 10; i++)
            //{
            //    T destroyMe = pooledObjects.Pop();
            //    UnityEngine.Object.Destroy(destroyMe);
            //    Debug.Log("Destroyed");
            //}

                pooledObjects.Clear();

            Debug.Log("Stack has been cleared");
        }
    }


    // 2 functions: a push and a pull 
    // The generic parameter is the type of object that will be stored. 
    // This way our push and pull functions know what types they will be handling
    // Not strictly necessary 
    public interface IPool<T>
    {
        T Pull();
        void Push(T t);
    }

    //Used to define objects that can be in the object pool. When used as intended the object pool can only contain types that implement the IPoolable interface.
    //Has an initialize function that takes in an Action. 
    //This action will get set in the object pool and is intented to be the function that returns to object to the pool. 
    //This action is then invoked inside of the ReturnToPool function. 

    public interface IPoolable<T>
    {
        void Initialize(System.Action<T> returnAction);
        void ReturnToPool();
    }
}

**Comment by onewheelstudio** [comment]
There shouldn't be any problem calling the DestroyPool function from outside the class. I tested it - just in case - with no problem. Was there an error thrown? Based on the second image above it looks like you could call the function.

The objects are only in the pool if they are disabled. So if the objects are still enabled "destroying the pool" won't destroy the objects themselves. Could it be that you are in fact calling the function, but not seeing the objects be destroyed?

I simplified and renamed the destroy pool function (you are not actually destroying the pool only the objects in it).

```
    public void DestroyPoolObjects()
    {
        foreach (T item in pooledObjects)
            GameObject.Destroy(item.gameObject);

        pooledObjects.Clear();
    }
```

This is the class that I am using to test. Note I am using Odin Inspector - without it the Button attributes won't work. 

```
using UnityEngine;
using OWS.ObjectPooling;

public class Testing : MonoBehaviour
{
    public GameObject things;
    public ObjectPool<PoolObject> poolObjects;

    private void OnEnable()
    {
        poolObjects = new ObjectPool<PoolObject>(things);
    }

    [Sirenix.OdinInspector.Button]
    private void Spawn()
    {
        poolObjects.Pull();
    }

    [Sirenix.OdinInspector.Button]
    private void ClearPool()
    {
        Debug.Log($"{poolObjects.pooledCount} things in the pool");
        poolObjects.DestroyPoolObjects();
    }
}
```

If that doesn't fix the issue let me know or come by the OWS discord (link in any video description).

**Comment by justinLifelike** [comment]
Awesome!! Thanks a lot!
It works, yes I made some mistakes in my thinking progress. 
Thank you for clearing that out.

Keep it up with your awesome work - we love it <3
