### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by Moolt** [onewheelstudio/Adventures-in-C-Sharp#2]
Hi,

I really appreciate the work you put into the samples. I would like to implement key rebinding based on your sample but wanted to check if it's okay for you to use it in my game.

Would you mind to add a license to the project - MIT for example?

Thanks again for this great repository 🙂

**Comment by onewheelstudio** [comment]
You are more than welcome to use anything I post here or on YouTube in your projects. My rebinding solution is mostly stolen from Unity's example - just a bit better IMO ;)

I'll look into adding a license to the repo.

**Comment by Moolt** [comment]
Thank you so much. This helped me save quite some time :)
